env:
  browser: true
  commonjs: true
  es6: true
  node: true
  mocha: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 2017
rules:
  indent:
    - warn
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  require-yield:
    - off
  no-console:
    - off
